### PR TITLE
Add autocomplete feature. Based on, but heavily adapted from, leaflet-search implementation.

### PR DESCRIPTION
**Pull request by jasco**
The feature is initially disabled. Enable by setting the L.control.GeoSearch option enableAutocomplete to true. Assumes that geosearch query will return a list of partial matches.

Feedback welcome.

### CODE REVIEW

**Comment by smeijer** [comment]
@jasco, I am aware that this PR was requested a long time ago. Any chance that you could apply a rebase on the latest version?

**Comment by vlasvlasvlas** [comment]
Does enableAutocomplete works with Esri provider?

**Comment by jasco** [comment]
@smeijer I has been a very long time indeed. Yes, I'll take a look at rebasing.

**Comment by jasco** [comment]
@vlasvlasvlas it can be integrated with esri but has not yet been.  An interface file is required construct the query to the service and parse the results.

**Comment by jasco** [comment]
@vlasvlasvlas I think I was mistaken above. I have been away from this project for a number of years.  If your provider returns partial matches then autocomplete should work with the provider as is.  I use a custom provider so I did not realize/recall until I just looked more closely that the default esri provider is equivalent.

**Comment by jasco** [comment]
@smeijer the pull request has been rebased.  I hope it proves helpful.

**Comment by vlasvlasvlas** [comment]
txs!

**Comment by MrSohey** [comment]
It does not seem to work for me , I'll dig into it but I'd like to know if it is working for someone else on the latest version of leaflet and L.GeoSearch

**Comment by falqn** [comment]
It's not working for me too.

**Comment by jasco** [comment]
@MrSohey, @falqn.  Thanks for giving it a try.  It should be working now.

**Comment by MrSohey** [comment]
It's working great ! Thanks @jasco

**Comment by smeijer** [comment]
I'm currently working on a big rewrite of this plugin. I'll take a look at this PR soon, to make it part of the (new)  core. 

Thanks.

**Comment by falqn** [comment]
Yes, it's working now. Nice to hear about new core soon @smeijer. It will be great to include autocomplete function from @jasco PR. It will be very useful if autocomplete will suggest some results and user can choose which one is correct, ex. there are many places named 'Newton' in US.

**Comment by jasco** [comment]
@MrSohey, @falqn, great to hear it is working now.

@smeijer Thanks for the status update. I look forward to seeing the new
release.

When you dig into it you will notice that the AutoComplete class supports
overriding of the rendering of the HTML for the autocomplete data with
onMakeSuggestionHTML. I do not expose it currently but being able to
override the rendering might be of value to the users.

**Comment by smeijer** [comment]
Fixed this in the `next` branch. Release `v2.0.0` be released before the end of this year. Currently usable trough:

```sh
npm install leaflet-geosearch@next --save
```

@jasco, Thanks so much for this contributions to this project. Both your contributions have been re-created into the `next` branch. Sorry for being able to "just merge your PR's".

**Pull request closed without merging**
