### PR TITLE
event.preventDefault for searchbox on enter. option "draggable"

### LINKED ISSUE #12: enter key focus
While using this in a custom metabox in a wordpress custom post type screen, I cannot use the Lgeosearch because if you type something in there and press enter key, this activates the wordpress publish post button which also has a keypress listener..

### PR DESCRIPTION
**Pull request by thet**
1) after pressing <enter> in the searchbox, do event.preventDefault and event.stopPropagation to prevent submit forms to be submitted. Fixes #12 

2) add option "draggable", so the marker can be drag/dropped after a search has been done.

### CODE REVIEW

**Comment by thet** [comment]
@smeijer ping

**Comment by smeijer** [comment]
@thet pong

I now see how old this little project really is, and how many issues and pull requests are left open. 

So, first, let me thank you all for the input. Despite the fact that I haven't responded to most of them, I really appreciate all your input. I will take care of all items very soon. Been a busy man lately, but I'll make some time. Please give me one or two weeks to get started.

**Comment by thet** [comment]
np

i'll try to rebase with master

**Comment by thet** [comment]
@smeijer i rebased my fork with current master

**Comment by smeijer** [comment]
Sorry it took me so long. Your work has been merged :) Thanks the PR.

**Comment by thet** [comment]
tnx and no problem!

**Pull request merged**
